/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as SustainabilityReportingRouteImport } from './routes/sustainability-reporting'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as StudentEngagementRouteImport } from './routes/student-engagement'
import { Route as SogoodRouteImport } from './routes/sogood'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as GreenLoyaltyRouteImport } from './routes/green-loyalty'
import { Route as GamificationRouteImport } from './routes/gamification'
import { Route as FanEngagementRouteImport } from './routes/fan-engagement'
import { Route as EmployeeEngagementRouteImport } from './routes/employee-engagement'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsumerEngagementRouteImport } from './routes/consumer-engagement'
import { Route as CitizenEngagementRouteImport } from './routes/citizen-engagement'
import { Route as BehavioralScienceRouteImport } from './routes/behavioral-science'
import { Route as AttendeeEngagementRouteImport } from './routes/attendee-engagement'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityReportingRoute = SustainabilityReportingRouteImport.update({
  id: '/sustainability-reporting',
  path: '/sustainability-reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentEngagementRoute = StudentEngagementRouteImport.update({
  id: '/student-engagement',
  path: '/student-engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const SogoodRoute = SogoodRouteImport.update({
  id: '/sogood',
  path: '/sogood',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const GreenLoyaltyRoute = GreenLoyaltyRouteImport.update({
  id: '/green-loyalty',
  path: '/green-loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const GamificationRoute = GamificationRouteImport.update({
  id: '/gamification',
  path: '/gamification',
  getParentRoute: () => rootRouteImport,
} as any)
const FanEngagementRoute = FanEngagementRouteImport.update({
  id: '/fan-engagement',
  path: '/fan-engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeEngagementRoute = EmployeeEngagementRouteImport.update({
  id: '/employee-engagement',
  path: '/employee-engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerEngagementRoute = ConsumerEngagementRouteImport.update({
  id: '/consumer-engagement',
  path: '/consumer-engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenEngagementRoute = CitizenEngagementRouteImport.update({
  id: '/citizen-engagement',
  path: '/citizen-engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const BehavioralScienceRoute = BehavioralScienceRouteImport.update({
  id: '/behavioral-science',
  path: '/behavioral-science',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeeEngagementRoute = AttendeeEngagementRouteImport.update({
  id: '/attendee-engagement',
  path: '/attendee-engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attendee-engagement': typeof AttendeeEngagementRoute
  '/behavioral-science': typeof BehavioralScienceRoute
  '/citizen-engagement': typeof CitizenEngagementRoute
  '/consumer-engagement': typeof ConsumerEngagementRoute
  '/contact': typeof ContactRoute
  '/employee-engagement': typeof EmployeeEngagementRoute
  '/fan-engagement': typeof FanEngagementRoute
  '/gamification': typeof GamificationRoute
  '/green-loyalty': typeof GreenLoyaltyRoute
  '/platform': typeof PlatformRoute
  '/sogood': typeof SogoodRoute
  '/student-engagement': typeof StudentEngagementRoute
  '/sustainability': typeof SustainabilityRoute
  '/sustainability-reporting': typeof SustainabilityReportingRoute
  '/use-cases': typeof UseCasesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attendee-engagement': typeof AttendeeEngagementRoute
  '/behavioral-science': typeof BehavioralScienceRoute
  '/citizen-engagement': typeof CitizenEngagementRoute
  '/consumer-engagement': typeof ConsumerEngagementRoute
  '/contact': typeof ContactRoute
  '/employee-engagement': typeof EmployeeEngagementRoute
  '/fan-engagement': typeof FanEngagementRoute
  '/gamification': typeof GamificationRoute
  '/green-loyalty': typeof GreenLoyaltyRoute
  '/platform': typeof PlatformRoute
  '/sogood': typeof SogoodRoute
  '/student-engagement': typeof StudentEngagementRoute
  '/sustainability': typeof SustainabilityRoute
  '/sustainability-reporting': typeof SustainabilityReportingRoute
  '/use-cases': typeof UseCasesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attendee-engagement': typeof AttendeeEngagementRoute
  '/behavioral-science': typeof BehavioralScienceRoute
  '/citizen-engagement': typeof CitizenEngagementRoute
  '/consumer-engagement': typeof ConsumerEngagementRoute
  '/contact': typeof ContactRoute
  '/employee-engagement': typeof EmployeeEngagementRoute
  '/fan-engagement': typeof FanEngagementRoute
  '/gamification': typeof GamificationRoute
  '/green-loyalty': typeof GreenLoyaltyRoute
  '/platform': typeof PlatformRoute
  '/sogood': typeof SogoodRoute
  '/student-engagement': typeof StudentEngagementRoute
  '/sustainability': typeof SustainabilityRoute
  '/sustainability-reporting': typeof SustainabilityReportingRoute
  '/use-cases': typeof UseCasesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/attendee-engagement'
    | '/behavioral-science'
    | '/citizen-engagement'
    | '/consumer-engagement'
    | '/contact'
    | '/employee-engagement'
    | '/fan-engagement'
    | '/gamification'
    | '/green-loyalty'
    | '/platform'
    | '/sogood'
    | '/student-engagement'
    | '/sustainability'
    | '/sustainability-reporting'
    | '/use-cases'
    | '/demo/start/api-request'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/attendee-engagement'
    | '/behavioral-science'
    | '/citizen-engagement'
    | '/consumer-engagement'
    | '/contact'
    | '/employee-engagement'
    | '/fan-engagement'
    | '/gamification'
    | '/green-loyalty'
    | '/platform'
    | '/sogood'
    | '/student-engagement'
    | '/sustainability'
    | '/sustainability-reporting'
    | '/use-cases'
    | '/demo/start/api-request'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/attendee-engagement'
    | '/behavioral-science'
    | '/citizen-engagement'
    | '/consumer-engagement'
    | '/contact'
    | '/employee-engagement'
    | '/fan-engagement'
    | '/gamification'
    | '/green-loyalty'
    | '/platform'
    | '/sogood'
    | '/student-engagement'
    | '/sustainability'
    | '/sustainability-reporting'
    | '/use-cases'
    | '/demo/start/api-request'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AttendeeEngagementRoute: typeof AttendeeEngagementRoute
  BehavioralScienceRoute: typeof BehavioralScienceRoute
  CitizenEngagementRoute: typeof CitizenEngagementRoute
  ConsumerEngagementRoute: typeof ConsumerEngagementRoute
  ContactRoute: typeof ContactRoute
  EmployeeEngagementRoute: typeof EmployeeEngagementRoute
  FanEngagementRoute: typeof FanEngagementRoute
  GamificationRoute: typeof GamificationRoute
  GreenLoyaltyRoute: typeof GreenLoyaltyRoute
  PlatformRoute: typeof PlatformRoute
  SogoodRoute: typeof SogoodRoute
  StudentEngagementRoute: typeof StudentEngagementRoute
  SustainabilityRoute: typeof SustainabilityRoute
  SustainabilityReportingRoute: typeof SustainabilityReportingRoute
  UseCasesRoute: typeof UseCasesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability-reporting': {
      id: '/sustainability-reporting'
      path: '/sustainability-reporting'
      fullPath: '/sustainability-reporting'
      preLoaderRoute: typeof SustainabilityReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-engagement': {
      id: '/student-engagement'
      path: '/student-engagement'
      fullPath: '/student-engagement'
      preLoaderRoute: typeof StudentEngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sogood': {
      id: '/sogood'
      path: '/sogood'
      fullPath: '/sogood'
      preLoaderRoute: typeof SogoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/green-loyalty': {
      id: '/green-loyalty'
      path: '/green-loyalty'
      fullPath: '/green-loyalty'
      preLoaderRoute: typeof GreenLoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamification': {
      id: '/gamification'
      path: '/gamification'
      fullPath: '/gamification'
      preLoaderRoute: typeof GamificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fan-engagement': {
      id: '/fan-engagement'
      path: '/fan-engagement'
      fullPath: '/fan-engagement'
      preLoaderRoute: typeof FanEngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-engagement': {
      id: '/employee-engagement'
      path: '/employee-engagement'
      fullPath: '/employee-engagement'
      preLoaderRoute: typeof EmployeeEngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer-engagement': {
      id: '/consumer-engagement'
      path: '/consumer-engagement'
      fullPath: '/consumer-engagement'
      preLoaderRoute: typeof ConsumerEngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen-engagement': {
      id: '/citizen-engagement'
      path: '/citizen-engagement'
      fullPath: '/citizen-engagement'
      preLoaderRoute: typeof CitizenEngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behavioral-science': {
      id: '/behavioral-science'
      path: '/behavioral-science'
      fullPath: '/behavioral-science'
      preLoaderRoute: typeof BehavioralScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendee-engagement': {
      id: '/attendee-engagement'
      path: '/attendee-engagement'
      fullPath: '/attendee-engagement'
      preLoaderRoute: typeof AttendeeEngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AttendeeEngagementRoute: AttendeeEngagementRoute,
  BehavioralScienceRoute: BehavioralScienceRoute,
  CitizenEngagementRoute: CitizenEngagementRoute,
  ConsumerEngagementRoute: ConsumerEngagementRoute,
  ContactRoute: ContactRoute,
  EmployeeEngagementRoute: EmployeeEngagementRoute,
  FanEngagementRoute: FanEngagementRoute,
  GamificationRoute: GamificationRoute,
  GreenLoyaltyRoute: GreenLoyaltyRoute,
  PlatformRoute: PlatformRoute,
  SogoodRoute: SogoodRoute,
  StudentEngagementRoute: StudentEngagementRoute,
  SustainabilityRoute: SustainabilityRoute,
  SustainabilityReportingRoute: SustainabilityReportingRoute,
  UseCasesRoute: UseCasesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
